name: "PlatformIO CI"

on: [push, pull_request, ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Beautiful Soup
        run: pip install beautifulsoup4

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO Check
        run: pio check --skip-packages

      - name: Build PlatformIO Project
        run: pio run
